import Head from 'next/head';
import styles from '../styles/Login.module.scss';

import { TextField } from '@mui/material';
import { useState } from 'react';

const Home = () => {
	const [user, setUser] = useState({});

	console.log(user);

	const handleChange = ({ target }) => {
		setUser({
			[target.name]: target.value,
		});
	};

	const handleSubmit = event => {
		event.preventDefault();
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Inicio de Sesion - Admin Dashboard</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<div className={styles.container}>
					<h1>Bienvenido Administrador</h1>
					<form className={styles.formContainer}>
						<TextField
							label='email'
							variant='outlined'
							onChange={handleChange}
							name='email'
						/>
						<TextField
							label='contraseña'
							type='password'
							variant='outlined'
							name='password'
						/>
						<button className={styles.button} onClick={handleSubmit}>
							Iniciar Sesion
						</button>
					</form>
				</div>
			</main>
		</div>
	);
};

export default Home;
