import Head from 'next/head';
import styles from '../styles/Login.module.scss';
import { useState } from 'react';

import KeyIcon from '@mui/icons-material/Key';
import AlternateEmailIcon from '@mui/icons-material/AlternateEmail';

const Home = () => {
	const [user, setUser] = useState({});

	console.log(user);

	const handleChange = ({ target }) => {
		setUser({
			[target.name]: target.value,
		});
	};

	const handleSubmit = event => {
		event.preventDefault();
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Inicio de Sesion - Admin Dashboard</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<div className={styles.container}>
					<h1>Bienvenido!</h1>
					<form className={styles.formContainer}>
						<div className={styles.inputContainer}>
							<AlternateEmailIcon sx={{ color: 'rgb(53, 139, 219)' }} />
							<input placeholder='email' onChange={handleChange} name='email' />
						</div>

						<div className={styles.inputContainer}>
							<KeyIcon sx={{ color: 'rgb(53, 139, 219)' }} />
							<input
								placeholder='contraseña'
								type='password'
								onChange={handleChange}
								name='password'
							/>
						</div>
						<button className={styles.button} onClick={handleSubmit}>
							Iniciar Sesion
						</button>
					</form>
				</div>
			</main>
		</div>
	);
};

export default Home;
