import Head from 'next/head';
import styles from '../styles/Home.module.scss';

export default function Home() {
	console.log('Holis');

	return (
		<div className={styles.container}>
			<Head>
				<title>Home Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Iniciando el proyecto</h1>
			</main>
		</div>
	);
}
